# Site Settings
locale                   : "es_ES"
title                    : "Emirodgar - Experto Digital"
title_separator          : "|"
name                     : "Emirodgar"
url                      : "https://emirodgar.com"
twitter_username: emirodgar
github_username:  emirodgar
logo: cdn/images/author/emirodgar-avatar.jpg
emirodgar:
  picture: cdn/images/author/emirodgar-avatar.jpg
  twitter: emirodgar
plugins: # previsously gems
  - jekyll-seo-tag
  - jekyll-redirect-from
feed:
  path: feed.xml
